FROM golang:1.25-alpine

WORKDIR /app

# Install git and other build essentials
RUN apk add --no-cache git build-base

# Install air for hot-reloading
RUN go install github.com/air-verse/air@latest

# Add GOBIN to PATH
ENV PATH="/go/bin:${PATH}"

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Run air to watch for changes
CMD ["air", "-c", ".air.toml"]
