// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: api/v1/tunnel.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlMessage_Type int32

const (
	ControlMessage_PING                 ControlMessage_Type = 0
	ControlMessage_PONG                 ControlMessage_Type = 1
	ControlMessage_RECONNECT            ControlMessage_Type = 2
	ControlMessage_CONFIG_UPDATE        ControlMessage_Type = 3
	ControlMessage_NOTIFY_LOCAL_OFFLINE ControlMessage_Type = 4
)

// Enum value maps for ControlMessage_Type.
var (
	ControlMessage_Type_name = map[int32]string{
		0: "PING",
		1: "PONG",
		2: "RECONNECT",
		3: "CONFIG_UPDATE",
		4: "NOTIFY_LOCAL_OFFLINE",
	}
	ControlMessage_Type_value = map[string]int32{
		"PING":                 0,
		"PONG":                 1,
		"RECONNECT":            2,
		"CONFIG_UPDATE":        3,
		"NOTIFY_LOCAL_OFFLINE": 4,
	}
)

func (x ControlMessage_Type) Enum() *ControlMessage_Type {
	p := new(ControlMessage_Type)
	*p = x
	return p
}

func (x ControlMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_tunnel_proto_enumTypes[0].Descriptor()
}

func (ControlMessage_Type) Type() protoreflect.EnumType {
	return &file_api_v1_tunnel_proto_enumTypes[0]
}

func (x ControlMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlMessage_Type.Descriptor instead.
func (ControlMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_tunnel_proto_rawDescGZIP(), []int{2, 0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`             // API Key yang didapat dari dashboard.
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                         // Versi biner agen.
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`                       // Nama host agen (untuk logging/identifikasi).
	MacAddress    string                 `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"` // Alamat MAC perangkat keras (untuk validasi trial).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_v1_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

type RegisterResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AssignedDomain string                 `protobuf:"bytes,2,opt,name=assigned_domain,json=assignedDomain,proto3" json:"assigned_domain,omitempty"` // Subdomain atau kustom domain yang diberikan.
	TunnelToken    string                 `protobuf:"bytes,3,opt,name=tunnel_token,json=tunnelToken,proto3" json:"tunnel_token,omitempty"`          // Token unik untuk enkripsi sesi tunneling.
	ErrorMessage   string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`       // Pesan jika registrasi gagal.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_v1_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetAssignedDomain() string {
	if x != nil {
		return x.AssignedDomain
	}
	return ""
}

func (x *RegisterResponse) GetTunnelToken() string {
	if x != nil {
		return x.TunnelToken
	}
	return ""
}

func (x *RegisterResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ControlMessage_Type    `protobuf:"varint,1,opt,name=type,proto3,enum=bizeto.v1.ControlMessage_Type" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // Data tambahan dalam format JSON atau string mentah.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_api_v1_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *ControlMessage) GetType() ControlMessage_Type {
	if x != nil {
		return x.Type
	}
	return ControlMessage_PING
}

func (x *ControlMessage) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_api_v1_tunnel_proto protoreflect.FileDescriptor

const file_api_v1_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x13api/v1/tunnel.proto\x12\tbizeto.v1\"\x81\x01\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1f\n" +
	"\vmac_address\x18\x04 \x01(\tR\n" +
	"macAddress\"\x9d\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fassigned_domain\x18\x02 \x01(\tR\x0eassignedDomain\x12!\n" +
	"\ftunnel_token\x18\x03 \x01(\tR\vtunnelToken\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xb6\x01\n" +
	"\x0eControlMessage\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.bizeto.v1.ControlMessage.TypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"V\n" +
	"\x04Type\x12\b\n" +
	"\x04PING\x10\x00\x12\b\n" +
	"\x04PONG\x10\x01\x12\r\n" +
	"\tRECONNECT\x10\x02\x12\x11\n" +
	"\rCONFIG_UPDATE\x10\x03\x12\x18\n" +
	"\x14NOTIFY_LOCAL_OFFLINE\x10\x042\xa4\x01\n" +
	"\rTunnelService\x12H\n" +
	"\rRegisterAgent\x12\x1a.bizeto.v1.RegisterRequest\x1a\x1b.bizeto.v1.RegisterResponse\x12I\n" +
	"\rControlStream\x12\x19.bizeto.v1.ControlMessage\x1a\x19.bizeto.v1.ControlMessage(\x010\x01B(Z&github.com/bizeto/bizeto-tunnel/api/v1b\x06proto3"

var (
	file_api_v1_tunnel_proto_rawDescOnce sync.Once
	file_api_v1_tunnel_proto_rawDescData []byte
)

func file_api_v1_tunnel_proto_rawDescGZIP() []byte {
	file_api_v1_tunnel_proto_rawDescOnce.Do(func() {
		file_api_v1_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_tunnel_proto_rawDesc), len(file_api_v1_tunnel_proto_rawDesc)))
	})
	return file_api_v1_tunnel_proto_rawDescData
}

var file_api_v1_tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1_tunnel_proto_goTypes = []any{
	(ControlMessage_Type)(0), // 0: bizeto.v1.ControlMessage.Type
	(*RegisterRequest)(nil),  // 1: bizeto.v1.RegisterRequest
	(*RegisterResponse)(nil), // 2: bizeto.v1.RegisterResponse
	(*ControlMessage)(nil),   // 3: bizeto.v1.ControlMessage
}
var file_api_v1_tunnel_proto_depIdxs = []int32{
	0, // 0: bizeto.v1.ControlMessage.type:type_name -> bizeto.v1.ControlMessage.Type
	1, // 1: bizeto.v1.TunnelService.RegisterAgent:input_type -> bizeto.v1.RegisterRequest
	3, // 2: bizeto.v1.TunnelService.ControlStream:input_type -> bizeto.v1.ControlMessage
	2, // 3: bizeto.v1.TunnelService.RegisterAgent:output_type -> bizeto.v1.RegisterResponse
	3, // 4: bizeto.v1.TunnelService.ControlStream:output_type -> bizeto.v1.ControlMessage
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_tunnel_proto_init() }
func file_api_v1_tunnel_proto_init() {
	if File_api_v1_tunnel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_tunnel_proto_rawDesc), len(file_api_v1_tunnel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_tunnel_proto_goTypes,
		DependencyIndexes: file_api_v1_tunnel_proto_depIdxs,
		EnumInfos:         file_api_v1_tunnel_proto_enumTypes,
		MessageInfos:      file_api_v1_tunnel_proto_msgTypes,
	}.Build()
	File_api_v1_tunnel_proto = out.File
	file_api_v1_tunnel_proto_goTypes = nil
	file_api_v1_tunnel_proto_depIdxs = nil
}
