FROM node:22-alpine

WORKDIR /app

ENV CI=true

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --no-frozen-lockfile

COPY . .

EXPOSE 6500

CMD ["pnpm", "dev", "--host", "0.0.0.0", "--port", "6500"]
